# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  clusterDomain: cluster.local
  updateStrategy: "RollingUpdate"
  editor: "Smartfy"
  namespace: "marketplace"
  domainName: "marketplace.finansystech.com.br"
  imagePullSecrets:
  - name: regsecret

########################
financeMarketplaceBackend:
  enabled: true
  name: finance-marketplace-backend
  image:
    repository: repo.aws.finansystech.com.br
    name: finansystech/finance-marketplace-backend
    tag: 0.1.0
    pullPolicy: Always
  env:
    - name: DATABASE_URI
      value: "mongodb://root:mongodb@shared-mongodb-0.shared-mongodb-headless.shared-mongodb.svc.cluster.local:27017,shared-mongodb-1.shared-mongodb-headless.shared-mongodb.svc.cluster.local:27017,shared-mongodb-2.shared-mongodb-headless.shared-mongodb.svc.cluster.local:27017"
    - name: PROXY_TARGET_PATH
      value: "https://payments.pabbly.com"
    - name: RUNTIME_BASE_PATH
      value: "https://api.devtools.full-dev.finansystech.com.br"
    - name: AUTH_SERVER_BASE_URL
      value: "https://keycloak.full-dev.finansystech.com.br/auth"
    - name: AUTH_SERVER_CLIENT_ID
      value: "admin-cli"
    - name: AUTH_SERVER_USERNAME
      value: "admin"
    - name: AUTH_SERVER_PASSWORD
      value: "f1n2021@"
    - name: AUTH_SERVER_REALM
      value: "Finansysbank"
  replicaCount: 1
  apiPort: 3000

  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 600Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    enabled: false

########################
financeMarketplaceFrontEnd:
  enabled: true
  name: finance-marketplace-frontend
  image:
    repository: repo.aws.finansystech.com.br
    name: finansystech/finance-marketplace-frontend
    tag: 0.1.0
    pullPolicy: Always
  env: {}
  replicaCount: 1
  apiPort: 8080

  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 600Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
    hosts:
      - host: admin.marketplace.finansystech.com.br
        paths:
          - /
    tls:
     - secretName: admin.marketplace.finansystech.com.br
       hosts:
         - admin.marketplace.finansystech.com.br
