# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  clusterDomain: cluster.local
  updateStrategy: "RollingUpdate"
  editor: "Smartfy"
  namespace: "fbank-dev"
  domainName: "dev.example.com"
  imagePullSecrets:
  - name: regsecret

########################
openfinanceCallbackFinansysbank:
  enabled: true
  name: openfinance-callback-finansysbank
  image:
    repository: repo.aws.finansystech.com.br
    name: finansystech/openfinance-callback-finansysbank
    tag: qa-0.0.1
    pullPolicy: Always
  env: {}
  replicaCount: 1
  apiPort: 8080

  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 600Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
    hosts:
      - host: callback.dev.fbank.full.finansystech.com.br
        paths: []
    tls:
     - secretName: callback.dev.fbank.full.finansystech.com.br
       hosts:
         - callback.dev.fbank.full.finansystech.com.br
