# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  clusterDomain: cluster.local
  updateStrategy: "RollingUpdate"
  editor: "Smartfy"
  namespace: "marketplace"
  domainName: "marketplace.finansystech.com.br"
  imagePullSecrets:
  - name: regsecret


########################
shotfyHabemus:
  enabled: true
  name: shotfy-habemus
  image:
    repository: 424559638657.dkr.ecr.us-east-2.amazonaws.com
    name: shotfy_helm_api_rails
    tag: 0.0.1
    pullPolicy: Always
  env:
    - name: PROXY_URL
      value: "http://finance-marketplace-backend.marketplace.svc.cluster.local:3000"
  replicaCount: 1
  apiPort: 31364

  app_collection:
    app_collection:
      apps: [
        "/habemus_container/config_habemus_container/instagram_stories/instagram_stories.json",
        "/habemus_container/config_habemus_container/highlights/instagram_highlights.json",
        "/habemus_container/config_habemus_container/whatsapp/whatsapp_app.json",
        "/habemus_container/config_habemus_container/pinterest/pinterest.json",
        "/habemus_container/config_habemus_container/instagram/instagram_app.json",
        "/habemus_container/config_habemus_container/tiktok/tiktok.json",
        "/habemus_container/config_habemus_container/twitter/twitter.json"
      ]

  resources:
    requests:
      cpu: 10m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 600Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/affinity: "cookie"
    hosts:
      - host: habemus-k8s.shotfy.com
        paths:
          - /
    tls:
     - secretName: habemus-k8s.shotfy.com
       hosts:
         - habemus-k8s.shotfy.com
