{{- if .Values.shotfyHabemus.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.shotfyHabemus.name }}
  namespace: {{ .Values.global.namespace }}
data:
  app_collection.json: |
    {{- with .Values.shotfyHabemus.app_collection }}
    app_collection: 
        {{- toJson . | nindent 6 }}
        {{- end }}
    {{- end}}
  habemus_config.json: |
      {
      
        "app_collection_path": "/habemus_container/config_habemus_container/app_collection.json"
      
      }